GET http://localhost:3000/api/articles

### получает публикацию по id
GET http://localhost:3000/api/articles/444

###
GET http://localhost:3000/api/articles/444/comments

###
GET http://localhost:3000/api/search?query=Ёлки

### создаёт новую публикацию
POST http://localhost:3000/api/articles
Content-Type: application/json

{
  "title": "Как собрать камни бесконечности",
  "announce": "Достичь успеха помогут ежедневные повторения. Js прочно вошёл в нашу жизнь. Пути назад нет. Простые ежедневные упражнения помогут достичь успеха. Вы можете достичь всего. Стоит только немного постараться и запастись книгами.",
  "fullText": "Достичь успеха помогут ежедневные повторения. Js прочно вошёл в нашу жизнь. Пути назад нет. Простые ежедневные упражнения помогут достичь успеха. Вы можете достичь всего. Стоит только немного постараться и запастись книгами.",
  "category": [
    "Деревья",
    "Железо"
  ]
}

### создаёт новую публикацию (ошибка валидации)
POST http://localhost:3000/api/articles
Content-Type: application/json

{
  "title": "Как собрать камни бесконечности",
  "announce": "Достичь успеха помогут ежедневные повторения. Js прочно вошёл в нашу жизнь. Пути назад нет. Простые ежедневные упражнения помогут достичь успеха. Вы можете достичь всего. Стоит только немного постараться и запастись книгами.",
  "fullText": "Достичь успеха помогут ежедневные повторения. Js прочно вошёл в нашу жизнь. Пути назад нет. Простые ежедневные упражнения помогут достичь успеха. Вы можете достичь всего. Стоит только немного постараться и запастись книгами."
}

### создаёт новый комментарий
POST http://localhost:3000/api/articles/444/comments
Content-Type: application/json

{
  "text": "Как собрать камни бесконечности"
}

### обновляет публикацию
PUT http://localhost:3000/api/articles/G1zuY9
Content-Type: application/json

{
  "title": "Как собрать камни бесконечности 3333",
  "announce": "Достичь успеха помогут ежедневные повторения. Js прочно вошёл в нашу жизнь. Пути назад нет. Простые ежедневные упражнения помогут достичь успеха. Вы можете достичь всего. Стоит только немного постараться и запастись книгами.",
  "fullText": "Достичь успеха помогут ежедневные повторения. Js прочно вошёл в нашу жизнь. Пути назад нет. Простые ежедневные упражнения помогут достичь успеха. Вы можете достичь всего. Стоит только немного постараться и запастись книгами.",
  "category": [
    "Деревья",
    "Железо"
  ]
}

### удаляет комментарий
DELETE http://localhost:3000/api/articles/333/comments/111

### удаляет публикацию
DELETE http://localhost:3000/api/articles/444
